apiVersion: apps/v1
kind: Deployment
metadata:
  name: fretweb
spec:
  selector:
    matchLabels:
      app: fretweb
  template:
    metadata:
      labels:
        app: fretweb
    spec:
      containers:
      - name: fretweb
        image: ghcr.io/markrendle/fretweb:2024.8480813676
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api
              key: key
        - name: CLOUDFLARE_API_ZONE
          valueFrom:
            secretKeyRef:
              name: cloudflare-api
              key: zone
      imagePullSecrets:
      - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fretweb
spec:
  selector:
    app: fretweb
  ports:
  - port: 80
