name: Build ARM Container Image

on:
  push:
    branches:
      ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: dotnet restore
        run: dotnet restore
      - name: dotnet test
        run: dotnet test -c Release --no-restore
      - name: dotnet publish
        run: dotnet publish -c Release --no-restore -o ./publish /p:UseAppHost=false src/FretWeb/FretWeb.csproj
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: DockerfileArm
          platforms: linux/arm64
          push: true
          tags: ghcr.io/markrendle/fretweb:2024.${{ github.run_id }}
